name: Sync to GCS bucket

on:
  push:
    branches: [ main ]
    paths: [ mindbook.2practice.xyz/** ]
  pull_request:
    branches: [ main ]

jobs:

  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nakilon/git-to-gcs@1
        with:
          secrets: ${{ secrets.SECRETS }}
